# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35296eee3794ada06b67a1654647fa5fb904134155a8df9837bf3396558e8f7fac52287aff041345e8f0d71017ae4b5ee1c3c11329e8e3d95e0effde09467652

test:
  secret_key_base: a10ee704339e55294e3a1258499808088843ff6c78c33136775ae8f5fa9225209b16444c175242a91495c2a9b591ca21ce41ffbce69140d409e7a87eef951da4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
